# Generated by Django 3.0.5 on 2020-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreminder',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
