# Generated by Django 3.0.5 on 2020-05-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='filters',
            new_name='file_filters',
        ),
        migrations.AddField(
            model_name='userstate',
            name='folder_filters',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
