# Generated by Django 3.0.5 on 2020-05-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200507_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='file_filters',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='folder_filters',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
