# Generated by Django 3.0.5 on 2020-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200509_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shared_with_me',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
