# Generated by Django 3.0.5 on 2020-06-29 02:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_shared_with_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_photo_path),
        ),
    ]
