# Generated by Django 3.0.5 on 2020-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200629_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin IT', 'Admin IT'), ('Admin Editor', 'Admin Editor'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=50),
        ),
    ]
