# Generated by Django 3.0.5 on 2020-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200802_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='total_storage',
            field=models.BigIntegerField(default=0),
        ),
    ]
