# Generated by Django 3.0.5 on 2020-05-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('folder', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('location', models.FileField(blank=True, null=True, upload_to=quiz.models.upload_quiz_path)),
                ('starred', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('sharable', models.BooleanField(default=False)),
                ('shared_with', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_editted', models.DateTimeField(blank=True, null=True)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('last_editted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editted_by_who', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quiz_Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
