# Generated by Django 3.0.5 on 2020-08-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizfilesystem',
            name='description',
        ),
        migrations.AddField(
            model_name='quizfilesystem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizfilesystem',
            name='note_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Note_quizzed_from', to='notes.FileSystem'),
        ),
        migrations.AddField(
            model_name='quizfilesystem',
            name='quiz_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizfilesystem',
            name='quiz_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizfilesystem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizfilesystem',
            name='taken_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
