# Generated by Django 3.0.5 on 2020-08-02 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('folder', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('location', models.FileField(blank=True, null=True, upload_to=notes.models.upload_image_path)),
                ('starred', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('sharable', models.BooleanField(default=False)),
                ('shared_with', models.CharField(blank=True, max_length=50, null=True)),
                ('words', models.CharField(blank=True, max_length=500, null=True)),
                ('time_taken', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('quized', models.BooleanField(default=False)),
                ('quized_saved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_editted', models.DateTimeField(blank=True, null=True)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('last_editted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editted_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
